"""The CLI entrypoints. `run` needs a live Postgres and a fetcher, so the
commands that only touch config, the contract or the database are tested
directly and `run` is exercised up to its first guard (missing DATABASE_URL).
"""
import pathlib

import pytest

from jobscout import __main__ as cli

ROOT = pathlib.Path(__file__).resolve().parents[1]
CASES = ROOT / "tests" / "contract_cases.yaml"


def test_env_flag_truthy_values(monkeypatch):
    for value in ("1", "true", "TRUE", "yes", " True "):
        monkeypatch.setenv("JOBSCOUT_TEST_FLAG", value)
        assert cli._env_flag("JOBSCOUT_TEST_FLAG") is True


def test_env_flag_falsy_values(monkeypatch):
    for value in ("0", "false", "no", "", "tru", "2"):
        monkeypatch.setenv("JOBSCOUT_TEST_FLAG", value)
        assert cli._env_flag("JOBSCOUT_TEST_FLAG") is False


def test_run_without_database_url_returns_2(monkeypatch):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    assert cli.main(["run"]) == 2


def test_check_passes_the_repo_contract(caplog):
    import logging

    caplog.set_level(logging.INFO)
    assert cli.main(["check", "--cases", str(CASES)]) == 0
    assert "contract cases pass" in caplog.text


def test_check_fails_on_a_case_that_contradicts_the_config(tmp_path):
    bad = tmp_path / "bad.yaml"
    bad.write_text(
        "titles:\n"
        "  - [Software Engineer Intern, true]\n"     # config says false
        "  - [DevOps Co-Op, false]\n"                # config says true\n"
        "locations: []\n"
        "levels: []\n"
    )
    assert cli.main(["check", "--cases", str(bad)]) == 1


def test_export_renders_markdown_table(monkeypatch, tmp_path):
    rows = [
        {"age_days": 3, "company": "Acme", "title": "Cloud Intern",
         "location": "Austin, TX", "terms": "Spring 2027",
         "url": "https://acme.example/jobs/1", "dedupe_key": "k1"},
        {"age_days": None, "company": "Beta", "title": "SRE Co-op",
         "location": "", "terms": "", "url": "", "dedupe_key": "k2"},
    ]
    class FakeConn:
        def close(self):
            pass

    conn = FakeConn()

    def fake_connect(_dsn):
        return conn

    def fake_open(_c, only_unnotified=True):
        return rows

    monkeypatch.setenv("DATABASE_URL", "postgresql://fake")
    monkeypatch.setattr(cli.database, "connect", fake_connect)
    monkeypatch.setattr(cli.database, "open_postings", fake_open)

    out = tmp_path / "out.md"
    assert cli.main(["export", "-o", str(out)]) == 0
    text = out.read_text()
    assert text.startswith("# jobscout matches (2 open)")
    assert "| 3d | Acme | Cloud Intern | Austin, TX | Spring 2027 | [apply](" in text
    assert "| ? | Beta | SRE Co-op | - | - | - |" in text


def test_export_without_database_url_returns_2(monkeypatch):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    assert cli.main(["export"]) == 2


def test_discover_writes_yaml_with_boards(monkeypatch, tmp_path):
    class FakeFetcher:
        def __init__(self):
            self.asked = []

        def __enter__(self):
            return self

        def __exit__(self, *exc):
            return None

        def get_text(self, url):
            self.asked.append(url)
            # One row with a singular /job/ URL and one with the Cisco-style
            # /jobs/ProjectDetail shape so both slug spellings surface.
            return (
                "<table><tr><th>Company</th><th>Role</th><th>Location</th>"
                "<th>Application</th><th>Age</th></tr>"
                "<tr><td>Example</td><td>IT Platform Intern</td><td>Austin, TX</td>"
                "<td><a href=\"https://boards.greenhouse.io/example/jobs/1\">apply</a></td>"
                "<td>0d</td></tr>"
                "<tr><td>Example</td><td>SRE Intern</td><td>Rochester, NY</td>"
                "<td><a href=\"https://boards.greenhouse.io/example2/jobs/2\">apply</a></td>"
                "<td>1d</td></tr>"
                "</table>"
            )

        def get_json(self, url):
            return {"jobs": []}

    monkeypatch.setattr(cli, "Fetcher", FakeFetcher)
    monkeypatch.setattr("jobscout.sources.simplify.FILES", {"simplify-s27": "https://raw.example/README.md"})

    out = tmp_path / "boards.yaml"
    assert cli.main(["discover-boards", "-o", str(out)]) == 0
    text = out.read_text()
    assert "generated by" in text
    assert "boards:" in text
    # Both slugs survive discovery, proving the plural /jobs/ shape (real
    # Phenom employers publish it) is not dropped.
    assert "example" in text and "example2" in text


def test_selftest_returns_zero():
    assert cli.main(["selftest"]) == 0


def test_unknown_command_exits_2(capsys):
    with pytest.raises(SystemExit) as exc:
        cli.main(["frobnicate"])
    assert exc.value.code == 2
    assert "usage" in capsys.readouterr().err.lower()